### PR TITLE
Feature add design teardown

### PR DESCRIPTION
**Pull request by Bluette1**
# Feature add design teardown
 - In this [project](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown), we try to imitate the appearance and layout of the [original page](https://www.smashingmagazine.com/).

This project is about

-  User Experience (UX) in Web Design.
  - Alignment of elements (mainly using Flex and/or CSS Grid)
  - Typography

[Live Demo](https://rawcdn.githack.com/Bluette1/design-teardown/1b086e30fa02c7add5f69ef9422928d7dd3d82b1/index.html)

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :ok_hand:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work! @Bluette1 and @chindrop :rocket: 
You have done really well building this, and I love how neat it looks. I have one request, however, with respect to your navigation bar. Please see my comment below:

#### Using divs
Please note that each element in the navigation bar should be wrapped in a `div` and this `div` should be used to provide adequate positioning. Please see the requirement below
screenshot

### Summary
Please make the changes to the structure and hence, the styling of your navigation, and thereafter, request another review. I wish you the very best and see you at the top! :medal_military: 

## Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Bluette1** [comment]
Thank you very much for your feedback @Oluwadamilareolusakin! We try to make the recommended changes shortly.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Impressive work :clap: Having verified you worked on the previously reviewed changes and your project looks good. I, therefore, approve of it. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Comment by Bluette1** [comment]
Okay, thank you very much @rOluochKe!

**Pull request merged**
